### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [jamescookie/Scrabble#1]
is it possiable like below in web-site 
pass the current board and it will return all playable words with starting position and direction.

http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by jamescookie** [comment]
Probably, but it was 7 years ago that I looked at this code and I'm not planning on maintaining it.
Feel free to branch the code and try...
